version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
    - playground/unit
    - pantheon/push:
        checkout: false
        pre-steps:
        - checkout
        - playground/composer_install_no_dev
        - run: composer prepare-for-pantheon
        - run: cat .gitignore
        - run: git status
        post-steps:
        - run: cd "/tmp/pantheon_repo" && git status
        - run: echo "testing CI on master branch"
        # These commands should be called from Quicksilver.
        # https://github.com/pantheon-systems/quicksilver-examples/
        - run: terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y
        - run: terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" cr
        - run: terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
    - cypress/run:
        requires:
        - playground/backstop
        store_artifacts: true
        pre-steps:
        - playground/setbashenv
        - run: echo 'export CYPRESS_baseUrl="${MULTIDEV_SITE_URL}"' >> $BASH_ENV
        - run: source $BASH_ENV

orbs:
  cypress: cypress-io/cypress@1
  playground: fauxalgore/playground@0.0.2
  pantheon: pantheon-systems/pantheon@0.2.0
