definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  system__admin_content:
    weight: -55
    menu_name: admin
    parent: system.admin
    enabled: true
    expanded: false
  system__admin_structure:
    weight: -54
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: -53
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: -52
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: -51
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: -50
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: -49
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  help__main:
    weight: -48
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
